CREATE DATABASE BD_BELATRIX
GO

USE BD_BELATRIX
GO

CREATE TABLE T_LOG (
	MESSAGE VARCHAR(200),
	MESSAGE_TYPE CHAR (1)
)
GO

CREATE PROCEDURE SP_SAVE_LOG (@MESSAGE VARCHAR(200), 
							  @MESSAGE_ID CHAR(1))
AS
	INSERT INTO T_LOG VALUES (@MESSAGE, @MESSAGE_ID);	
GO